### ISSUE TITLE
如何使用结构中嵌套基本类型的容器

### ISSUE THREAD

**Issue by Virgo-gitch** [HuaGouFdog/FdogSerialize#52]
struct Test{
int a;
std::vector<int> v;
REGISTERED_MEMBER_S(Test, a, v);
};

编译时显示/home/aoi/project/test/untitled2/FStruct.h:1536: error: ‘class std::vector< int>’ has no member named ‘Serialize_struct_s’
   object_.Serialize_struct_s(json_, json_s, object_, metainfoObject);
   ~~~~~~~~^~~~~~~~~~~~~~~~~~

**Comment by HuaGouFdog** [comment]
抱歉，前几天优化使用方式遗留了一些东西。
请修改为：
struct Test{
int a;
std::vector <int&gt; v;
REGISTERED_MEMBER_S(Test, a, v);
};template<&gt; struct TagDispatchTrait_zx<vector<int&gt;&gt; {using Tag = BaseTag_zx;};


后续我会把template<&gt; struct TagDispatchTrait_zx<vector<int&gt;&gt; {using Tag = BaseTag_zx;};加入库


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuaGouFdog/FdogSerialize"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午3:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HuaGouFdog/FdogSerialize] 如何使用结构中嵌套基本类型的容器 (Issue #52)





 
struct Test{
 int a;
 std::vector v;
 REGISTERED_MEMBER_S(Test, a, v);
 };
 
编译时显示/home/aoi/project/test/untitled2/FStruct.h:1536: error: ‘class std::vector< int&gt;’ has no member named ‘Serialize_struct_s’
 object_.Serialize_struct_s(json_, json_s, object_, metainfoObject);

**Comment by Virgo-gitch** [comment]
谢谢大佬!



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 花狗fdog ***@***.***&gt;
发送时间: 2023年4月4日 15:51
收件人: HuaGouFdog/FdogSerialize ***@***.***&gt;
抄送: Virgo-gitch ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [HuaGouFdog/FdogSerialize] 如何使用结构中嵌套基本类型的容器 (Issue #52)





 抱歉，前几天优化使用方式遗留了一些东西。 
 请修改为： 
 struct Test{ 
 int a; 
 std::vector <int&amp;gt; v; 
 REGISTERED_MEMBER_S(Test, a, v); 
 };template<&amp;gt; struct TagDispatchTrait_zx<vector<int&amp;gt;&amp;gt; {using Tag = BaseTag_zx;}; 
 
 
 后续我会把template<&amp;gt; struct TagDispatchTrait_zx<vector<int&amp;gt;&amp;gt; {using Tag = BaseTag_zx;};加入库 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "HuaGouFdog/FdogSerialize"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年4月4日(星期二) 下午3:38 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[HuaGouFdog/FdogSerialize] 如何使用结构中嵌套基本类型的容器 (Issue #52) 
 
 
 
 
 
   
 struct Test{ 
  int a; 
  std::vector v; 
  REGISTERED_MEMBER_S(Test, a, v); 
  }; 
   
 编译时显示/home/aoi/project/test/untitled2/FStruct.h:1536: error: ‘class std::vector< int&amp;gt;’ has no member named ‘Serialize_struct_s’ 
  object_.Serialize_struct_s(json_, json_s, object_, metainfoObject);

**Comment by Virgo-gitch** [comment]
序列化的化结果应该是 
{"num":1,"nums":[2,3,4]}




但是实际输出是

{"num":1,"nums":[2,3,42,3,4]}





大佬， 是不是在内部转化的时候多了一次？是的话应该在哪里改？麻烦指导一下， 谢谢！



1650761032
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuaGouFdog/FdogSerialize"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuaGouFdog/FdogSerialize] 如何使用结构中嵌套基本类型的容器 (Issue #52)





 抱歉，前几天优化使用方式遗留了一些东西。 
 请修改为： 
 struct Test{ 
 int a; 
 std::vector <int&amp;gt; v; 
 REGISTERED_MEMBER_S(Test, a, v); 
 };template<&amp;gt; struct TagDispatchTrait_zx<vector<int&amp;gt;&amp;gt; {using Tag = BaseTag_zx;}; 
 
 
 后续我会把template<&amp;gt; struct TagDispatchTrait_zx<vector<int&amp;gt;&amp;gt; {using Tag = BaseTag_zx;};加入库 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "HuaGouFdog/FdogSerialize"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年4月4日(星期二) 下午3:38 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[HuaGouFdog/FdogSerialize] 如何使用结构中嵌套基本类型的容器 (Issue #52) 
 
 
 
 
 
   
 struct Test{ 
  int a; 
  std::vector v; 
  REGISTERED_MEMBER_S(Test, a, v); 
  }; 
   
 编译时显示/home/aoi/project/test/untitled2/FStruct.h:1536: error: ‘class std::vector< int&amp;gt;’ has no member named ‘Serialize_struct_s’ 
  object_.Serialize_struct_s(json_, json_s, object_, metainfoObject);

**Comment by HuaGouFdog** [comment]
是的，内部多转换了一次，请将FStruct.h第2518行
`    }else if (size > -1 && metainfoObject->memberTypeInt == OBJECT_VECTOR && metainfoObject->memberType == FdogSerializer::Instance()->getTypeName(typeid(object_.arg1).name())) {\`

改为
`    }else if (size > -1 && metainfoObject->memberTypeInt == OBJECT_VECTOR && metainfoObject->memberType == FdogSerializer::Instance()->getTypeName(typeid(object_.arg1).name()) && metainfoObject->first != "int") {\`

今晚我会修复这两个问题

**Comment by Virgo-gitch** [comment]
ok，已解决，大佬辛苦了！


1650761032
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuaGouFdog/FdogSerialize"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuaGouFdog/FdogSerialize] 如何使用结构中嵌套基本类型的容器 (Issue #52)





 
是的，内部多转换了一次，请将FStruct.h第2518行
     }else if (size &gt; -1 &amp;&amp; metainfoObject-&gt;memberTypeInt == OBJECT_VECTOR &amp;&amp; metainfoObject-&gt;memberType == FdogSerializer::Instance()-&gt;getTypeName(typeid(object_.arg1).name())) {\
 
改为
     }else if (size &gt; -1 &amp;&amp; metainfoObject-&gt;memberTypeInt == OBJECT_VECTOR &amp;&amp; metainfoObject-&gt;memberType == FdogSerializer::Instance()-&gt;getTypeName(typeid(object_.arg1).name()) &amp;&amp; metainfoObject-&gt;first != "int") {\
 
今晚我会修复这两个问题

**Comment by HuaGouFdog** [comment]
已解决

**Comment by HuaGouFdog** [comment]
1

**Comment by Virgo-gitch** [comment]
已解决
