### ISSUE TITLE
现在不在支持struct结构体转json了吗

### ISSUE THREAD

**Issue by chendj0710** [HuaGouFdog/FdogSerialize#54]
你好，我发现example/testType.h大多都是通过添加F_CLASS（xxx）将其转换成类的形式，只有struct TestType是结构体的形式。
但是在example.cpp中放开下面代码,编译就会报错
   ``` c
  REGISTEREDMEMBER(TestType, age1, age2, age3, age4, age5, age6, age7, age8);
  ```
报错内容
>In file included from testType.h:5:0,
                 from example.cpp:14:
example.cpp: In function ‘int main()’:
../FStruct.h:2463:1: error: expected primary-expression before ‘public’
 public:\

是现在不再支持struct xxx, 然后调用REGISTEREDMEMBER注册成员的方式了吗，还是我的使用有问题呀

**Comment by HuaGouFdog** [comment]
支持的，REGISTEREDMEMBER(TestType, age1, age2, age3, age4, age5, age6, age7, age8); 这种是早期实现的非入侵式的写法，后面发现不如侵入式好维护，就改了注册方式，直接在结构体内部注册，就是F_CLASS，可以看一下readme，要使用新的方法。

**Comment by HuaGouFdog** [comment]
是的，现在不支持struct xxx, 然后调用REGISTEREDMEMBER注册了，大量结构体不好维护，不如在定义处维护方便。

**Comment by chendj0710** [comment]
好的，谢谢

> 是的，现在不支持struct xxx, 然后调用REGISTEREDMEMBER注册了，大量结构体不好维护，不如在定义处维护方便。

**Comment by HuaGouFdog** [comment]
结束
